### ISSUE TITLE
Error while importing module 'odoo-vtiger-12.0': 'depends'

### ISSUE THREAD

**Issue by bscs201401** [JayVora-SerpentCS/odoo-vtiger#7]
I have downloaded the latest version odoo-vtiger-12.0 from GitHub. But while importing it into odoo v12.0 (https://proaudiony.odoo.com/web?) I faced this problem:

Error while importing module 'odoo-vtiger-12.0': 'depends'

[Error Screen Shot](https://prnt.sc/ncs8r1)

Please help ASAP to solve out this problem.

**Comment by saif-serpentcs** [comment]
Hello,

I will check it in v12 and fix it ASAP!

Thank you.

**Comment by bscs201401** [comment]
Thanks! I'm waiting.

**Comment by saif-serpentcs** [comment]
Hello Muhammad,

I checked it twice in v12, but, am not faced any errors.

Also, here attached the screenshots :
![Apps](https://user-images.githubusercontent.com/21328778/56264188-4ad85b00-6103-11e9-803e-bd5675f912c4.png)
![Products](https://user-images.githubusercontent.com/21328778/56264193-4f9d0f00-6103-11e9-8f34-a6a86c8aefaa.png)

Thank you!

**Comment by bscs201401** [comment]
Sir but I am still facing the same issue. Could you please help me in
solving this issue, I share the credentials of the site. please share your
email id.

**Comment by saif-serpentcs** [comment]
Ok, sure Muhammad,

email: s.rupwala.serpentcs@gmail.com
skype: saif_serpentcs

Thank you

**Comment by bscs201401** [comment]
@saif-serpentcs help me out of the right procedure for importing the odoo-vtiger v12.0 module.

**Comment by saif-serpentcs** [comment]
Hello Muhammad,

Installed your required modules, then go to the company -> vTiger configuration Tab.

![odoo_config](https://user-images.githubusercontent.com/21328778/56268284-95aba000-610e-11e9-956c-8446818b7e74.png)

Example: Click on **sync Products** Button, then go to products master menu
![Products   Odoo](https://user-images.githubusercontent.com/21328778/56268600-5f225500-610f-11e9-957c-022f58195499.png)

That is a procedure for importing the odoo-vtiger v12.0 module.

Thank you!
